root: /

Home: /

language: zh-CN

author: iGuan7u & Dustin
description: A beautiful & simple theme.

# AvatorURL
# it would be shown on sidecar.

avatar: 

# Comment

gitalk:
  enable: false
  clientID: 
  clientSecret: 
  repo: Gitalk
  owner: 
  admin: 

disqus:
  enable: false
  shortname: your_disqus_short_name

# Contact_Info
# Contact info will be shown on the side bar.

contact:
  enable: false
  email: 
  wechat: 

  github:
    enable: false
    username: 

  linkedin:
    enable: false
    username: 
  
  zhihu:
    enable: false
    username: 


# Analytice

baidu_analytics:
  enable: false
  id: 

mta_analytics:
  enable: false
  name: mta_analytics_name
  sid: mta_analytics_sid

google_analytice:
  enable: false
  tracking_id: google_tracking_id

# Website ICPLicense
# which is useful in China mainland.

ICPLicense:
  enable: false
  content: "Fill IPCLicense"

# EtraPlugin

extra_plugin:
  enable: false
  url: extra_plugin_js_url

# Development Setting

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false

