root: /

Home: /

language: zh-CN

author: iGuan7u & Dustin
description: A beautiful & simple theme.

# AvatorURL
# it would be shown on sidecar.

avatar: /assets/LOGO-green.png

# Comment

gitalk:
  enable: true
  clientID: 447058976c8bd4fe04f6
  clientSecret: 338d276a77fb63da17761fc5f39458092c228396
  repo: Gitalk
  owner: TimeGarage
  admin: TimeGarage

disqus:
  enable: false
  shortname: your_disqus_short_name

# Contact_Info
# Contact info will be shown on the side bar.

contact:
  enable: true
  description: 'Email: 82610725@163.com'

  twitter:
    enable: false
    username: twitter_username

  github:
    enable: true
    username: TimeGarage

  weibo:
    enable: false
    username: weibo_username

  facebook:
    enable: false
    username: facebook_username

  instagram:
    enable: false
    username: instagram_username


# Analytice

mta_analytics:
  enable: false
  name: mta_analytics_name
  sid: mta_analytics_sid

baidu_analytics:
  enable: false
  id: baidu_analytice_id

google_analytice:
  enable: false
  tracking_id: google_tracking_id

# Website ICPLicense
# which is useful in China mainland.

ICPLicense:
  enable: false
  content: "Fill IPCLicense"

# EtraPlugin

extra_plugin:
  enable: false
  url: extra_plugin_js_url

# Development Setting

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false