root: /

menu:
  Home: /
  Archives: /archives
  Tags: /tags

language: zh-CN

author: iGuan7u & Dustin
description: A beautiful & simple theme.

# AvatorURL
# it would be shown on sidecar.

avatar: /assets/LOGO-green.png

# Comment

disqus:
  enable: false
  shortname: your_disqus_short_name

# Contact_Info
# Contact info will be shown on the side bar.

contact:
  enable: true
  email: '82610725@163.com'
  wechat: TimeGarage

  github:
    enable: true
    username: TimeGarage

  linkedin:
    enable: false
    username: dustinpeng
  
  zhihu:
    enable: false
    username: brexit


# Analytice

mta_analytics:
  enable: false
  name: mta_analytics_name
  sid: mta_analytics_sid

google_analytice:
  enable: false
  tracking_id: google_tracking_id

# Website ICPLicense
# which is useful in China mainland.

ICPLicense:
  enable: false
  content: "Fill IPCLicense"

# EtraPlugin

extra_plugin:
  enable: false
  url: extra_plugin_js_url

# Development Setting

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false