<title>{{ page.title || config.subtitle || '' }}</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=2.0">
<link rel="stylesheet", href="{{ url_for('./css/style.css') }}">
<link rel="shortcut icon", href="{{ url_for('./assets/favicon.ico') }}">
<link rel="apple-touch-icon", sizes="128x128", href="{{ url_for('./assets/tree-128x128.png') }}">
